F1_Project/Models/Round.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace F1_Project.Models
{
    public class Round
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field can't be empty")]
        [Range(1, int.MaxValue, ErrorMessage = "This field cant be less or equal than zero")]
        public int Number { get; set; }

        // Chaves estrangeiras
        public int ChampionshipId { get; set; }
        public Championship Championship { get; set; }

        public int CircuitId { get; set; }
        public Circuit Circuit { get; set; }

        //public int DriverId { get; set; }
        //public Driver WinningDriver { get; set; }
        //public int TeamId { get; set; }
        //public Team WinningTeam { get; set; }
    }
}

F1_Project/Controllers/ChampionshipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using F1_Project.Data;
using F1_Project.Models;
using F1_Project.Models.ViewModel;

namespace F1_Project
{
    public class ChampionshipsController : Controller
    {
        private readonly DBContext _context;

        public ChampionshipsController(DBContext context)
        {
            _context = context;
        }

        // GET: Championships
        public async Task<IActionResult> Index(int? id)
        {
            var viewModel = new DriverIndexData();
            viewModel.Championships = await _context.Championships
                .Include(d => d.ChampionshipTeams)
                    .ThenInclude(d => d.Team)
                .AsNoTracking().OrderBy(d => d.Year).ToListAsync();

            if (id != null)
            {
                ViewData["ChampionshipId"] = id.Value;
                Championship championship = viewModel.Championships.Where(d => d.Id == id.Value).Single();
                viewModel.Teams = championship.ChampionshipTeams.Select(d => d.Team);
            }
            return View(viewModel);
        }

        // GET: Championships/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var viewModel = new DriverIndexData();
            viewModel.Championships = await _context.Championships
                .Include(d => d.ChampionshipTeams)
                    .ThenInclude(d => d.Team)
                .AsNoTracking().OrderBy(d => d.Year).ToListAsync();

            if (id != null)
            {
                ViewData["ChampionshipId"] = id.Value;
                Championship championship = viewModel.Championships.Where(d => d.Id == id.Value).Single();
                viewModel.Teams = championship.ChampionshipTeams.Select(d => d.Team);
            }

            return View(viewModel);
        }

        // GET: Championships/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Championships/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Year")] Championship championship)
        {
            if (ModelState.IsValid)
            {
                _context.Add(championship);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(championship);
        }

        // GET: Championships/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championship = await _context.Championships.FindAsync(id);
            if (championship == null)
            {
                return NotFound();
            }
            return View(championship);
        }

        // POST: Championships/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Year")] Championship championship)
        {
            if (id != championship.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(championship);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChampionshipExists(championship.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(championship);
        }

        // GET: Championships/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championship = await _context.Championships
                .FirstOrDefaultAsync(m => m.Id == id);
            if (championship == null)
            {
                return NotFound();
            }

            return View(championship);
        }

        // POST: Championships/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var championship = await _context.Championships.FindAsync(id);
            _context.Championships.Remove(championship);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChampionshipExists(int id)
        {
            return _context.Championships.Any(e => e.Id == id);
        }
    }
}

F1_Project/Controllers/RoundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using F1_Project.Data;
using F1_Project.Models;

namespace F1_Project.Controllers
{
    public class RoundsController : Controller
    {
        private readonly DBContext _context;

        public RoundsController(DBContext context)
        {
            _context = context;
        }

        // GET: Rounds
        public async Task<IActionResult> Index(int? championshipId)
        {
            ViewData["ChampionshipId"] = championshipId;
            if(championshipId != null)
            {
                // Ordena primeiro pelo Id do campeonato enviado no Details do Championship
                var dBContext = _context.Rounds.Include(r => r.Championship).Include(r => r.Circuit).Where(r => r.ChampionshipId == championshipId).OrderBy(r => r.Number);                
                return View(await dBContext.ToListAsync());
            }
            else
            {
                // Ordena primeiro pelo Year do Championship e depois pelo Number da Round
                var dBContext = _context.Rounds.Include(r => r.Championship).Include(r => r.Circuit).OrderByDescending(r => r.Championship.Year).ThenBy(r => r.Number);
                return View(await dBContext.ToListAsync());
            }          
        }

        // GET: Rounds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var round = await _context.Rounds
                .Include(r => r.Championship)
                .Include(r => r.Circuit)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (round == null)
            {
                return NotFound();
            }

            return View(round);
        }

        // GET: Rounds/Create
        public IActionResult Create(int? championshipId)
        {
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year");
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,ChampionshipId,CircuitId")] Round round)
        {
            if (ModelState.IsValid)
            {
                _context.Add(round);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", round.ChampionshipId);
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName", round.CircuitId);
            return View(round);
        }

        // GET: Rounds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var round = await _context.Rounds.FindAsync(id);
            if (round == null)
            {
                return NotFound();
            }
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", round.ChampionshipId);
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName", round.CircuitId);
            return View(round);
        }

        // POST: Rounds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,ChampionshipId,CircuitId")] Round round)
        {
            if (id != round.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(round);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoundExists(round.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", round.ChampionshipId);
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName", round.CircuitId);
            return View(round);
        }

        // GET: Rounds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var round = await _context.Rounds
                .Include(r => r.Championship)
                .Include(r => r.Circuit)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (round == null)
            {
                return NotFound();
            }

            return View(round);
        }

        // POST: Rounds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var round = await _context.Rounds.FindAsync(id);
            _context.Rounds.Remove(round);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoundExists(int id)
        {
            return _context.Rounds.Any(e => e.Id == id);
        }
    }
}

F1_Project/Views/Rounds/Create.cshtml
@model F1_Project.Models.Round

@{
    ViewData["Title"] = "New round";
}


<h4>Add a Round to the F1 calendar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampionshipId" class="control-label">Championship Year</label>
                <select asp-for="ChampionshipId" class ="form-control" asp-items="ViewBag.ChampionshipId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CircuitId" class="control-label">Circuit</label>
                <select asp-for="CircuitId" class ="form-control" asp-items="ViewBag.CircuitId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" />
                <a asp-action="Index" asp-controller="Home" class="btn btn-primary">Back</a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

F1_Project/Views/Rounds/Delete.cshtml
@model F1_Project.Models.Round

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>  
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>

F1_Project/Views/Rounds/Details.cshtml
@model F1_Project.Models.Round

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Round</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Championship)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Championship.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Circuit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Circuit.FullName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

F1_Project/Views/Rounds/Edit.cshtml
@model F1_Project.Models.Round

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Round</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampionshipId" class="control-label">Championship Year</label>
                <select asp-for="ChampionshipId" class="form-control" asp-items="ViewBag.ChampionshipId"></select>
                <span asp-validation-for="ChampionshipId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CircuitId" class="control-label">Circuit</label>
                <select asp-for="CircuitId" class="form-control" asp-items="ViewBag.CircuitId"></select>
                <span asp-validation-for="CircuitId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

F1_Project/Views/Rounds/Index.cshtml
@model IEnumerable<F1_Project.Models.Round>

@{
    ViewData["Title"] = "F1 Calendar";
}

<h3>F1 Calendar</h3>

<p>
    <a asp-action="Create" asp-route-championshipid="@ViewData["ChampionshipId"]" class="btn btn-info footer-color">Add new Round</a>
    <a asp-action="Details" asp-controller="Championships" asp-route-id="@ViewData["ChampionshipId"]" class="btn btn-primary">Back</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Year
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Circuit)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>   
            <td>
                @Html.DisplayFor(modelItem => item.Championship.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Circuit.FullName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-secondary">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>