F1_Project/Controllers/ChampionshipTeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using F1_Project.Data;
using F1_Project.Models;

namespace F1_Project.Controllers
{
    public class ChampionshipTeamsController : Controller
    {
        private readonly DBContext _context;

        public ChampionshipTeamsController(DBContext context)
        {
            _context = context;
        }

        // GET: ChampionshipTeams
        public async Task<IActionResult> Index()
        {
            var dBContext = _context.ChampionshipTeams.Include(c => c.Championship).Include(c => c.Team);
            return View(await dBContext.ToListAsync());
        }

        // GET: ChampionshipTeams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championshipTeam = await _context.ChampionshipTeams
                .Include(c => c.Championship)
                .Include(c => c.Team)
                .FirstOrDefaultAsync(m => m.ChampionshipId == id);
            if (championshipTeam == null)
            {
                return NotFound();
            }

            return View(championshipTeam);
        }

        // GET: ChampionshipTeams/Create
        public IActionResult Create(int? championshipId, int? teamId)
        {
            // Como Id não é chave primária, não há auto-incremento
            IEnumerable<int> ids = _context.ChampionshipTeams.Select(dt => dt.Id).ToList();
            ViewData["NewId"] = ids.Last() + 1;

            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year");
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName");
            return View();
        }

        // POST: ChampionshipTeams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ChampionshipId,TeamId")] ChampionshipTeam championshipTeam)
        {
            if (ModelState.IsValid)
            {
                _context.Add(championshipTeam);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Id", championshipTeam.ChampionshipId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName", championshipTeam.TeamId);
            return View(championshipTeam);
        }

        // GET: ChampionshipTeams/Edit/5
        public IActionResult Edit(int? championshipId, int? teamId)
        {
            ChampionshipTeam championshipTeamTemp = _context.ChampionshipTeams.Find(championshipId, teamId);

            if (championshipTeamTemp == null)
            {
                return NotFound();
            }
            
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", championshipTeamTemp.ChampionshipId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName", championshipTeamTemp.TeamId);
            return View(championshipTeamTemp);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,ChampionshipId,TeamId")] ChampionshipTeam championshipTeam)
        {
            // Chaves compostas => https://www.codeproject.com/Articles/797444/ASP-NET-MVC-Edit-Primary-Key-Values-for-Composite

            if (id != championshipTeam.ChampionshipId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                int championshipIdTemp = Convert.ToInt32(championshipTeam.ChampionshipId);
                int teamIdTemp = Convert.ToInt32(championshipTeam.TeamId);

                var services = _context.ChampionshipTeams.Single(dt => dt.Id == championshipTeam.Id);
                _context.ChampionshipTeams.Remove(services);
                _context.ChampionshipTeams.Add(championshipTeam);
                try
                {
                    _context.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Index");
                }
                _context.Entry(championshipTeam).State = EntityState.Modified;
                return RedirectToAction("Index");
            }
            
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", championshipTeam.ChampionshipId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName", championshipTeam.TeamId);
            return View(championshipTeam);
        }

        // GET: ChampionshipTeams/Delete/5
        public async Task<IActionResult> Delete(int? championshipId, int? teamId)
        {
            if (championshipId == null || teamId == null)
            {
                return NotFound();
            }

            var championshipTeam = await _context.ChampionshipTeams
                .Include(c => c.Championship)
                .Include(c => c.Team)
                .FirstOrDefaultAsync(m => m.ChampionshipId == championshipId && m.TeamId == teamId);
            if (championshipTeam == null)
            {
                return NotFound();
            }

            return View(championshipTeam);
        }

        // POST: ChampionshipTeams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int championshipId, int teamId)
        {
            var championshipTeam = await _context.ChampionshipTeams.FindAsync(championshipId, teamId);
            _context.ChampionshipTeams.Remove(championshipTeam);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChampionshipTeamExists(int championshipId, int teamId)
        {
            return _context.ChampionshipTeams.Any(e => e.ChampionshipId == championshipId && e.TeamId == teamId);
        }
    }
}

F1_Project/Controllers/ChampionshipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using F1_Project.Data;
using F1_Project.Models;
using F1_Project.Models.ViewModel;

namespace F1_Project
{
    public class ChampionshipsController : Controller
    {
        private readonly DBContext _context;

        public ChampionshipsController(DBContext context)
        {
            _context = context;
        }

        // GET: Championships
        public async Task<IActionResult> Index(int? id)
        {
            var viewModel = new DriverIndexData();
            viewModel.Championships = await _context.Championships
                .Include(d => d.ChampionshipTeams)
                    .ThenInclude(d => d.Team)
                .AsNoTracking().OrderBy(d => d.Year).ToListAsync();

            if (id != null)
            {
                ViewData["ChampionshipId"] = id.Value;
                Championship championship = viewModel.Championships.Where(d => d.Id == id.Value).Single();
                viewModel.Teams = championship.ChampionshipTeams.Select(d => d.Team);
            }
            return View(viewModel);
        }

        // GET: Championships/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var viewModel = new DriverIndexData();
            viewModel.Championships = await _context.Championships
                .Include(d => d.ChampionshipTeams)
                    .ThenInclude(d => d.Team)
                .AsNoTracking().OrderBy(d => d.Year).ToListAsync();

            if (id != null)
            {
                ViewData["ChampionshipId"] = id.Value;
                Championship championship = viewModel.Championships.Where(d => d.Id == id.Value).Single();
                viewModel.Teams = championship.ChampionshipTeams.Select(d => d.Team);
            }

            return View(viewModel);
        }

        // GET: Championships/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Championships/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Year")] Championship championship)
        {
            if (ModelState.IsValid)
            {
                _context.Add(championship);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(championship);
        }

        // GET: Championships/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championship = await _context.Championships.FindAsync(id);
            if (championship == null)
            {
                return NotFound();
            }
            return View(championship);
        }

        // POST: Championships/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Year")] Championship championship)
        {
            if (id != championship.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(championship);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChampionshipExists(championship.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(championship);
        }

        // GET: Championships/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var championship = await _context.Championships
                .FirstOrDefaultAsync(m => m.Id == id);
            if (championship == null)
            {
                return NotFound();
            }

            return View(championship);
        }

        // POST: Championships/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var championship = await _context.Championships.FindAsync(id);
            _context.Championships.Remove(championship);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChampionshipExists(int id)
        {
            return _context.Championships.Any(e => e.Id == id);
        }
    }
}

F1_Project/Controllers/RoundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using F1_Project.Data;
using F1_Project.Models;

namespace F1_Project.Controllers
{
    public class RoundsController : Controller
    {
        private readonly DBContext _context;

        public RoundsController(DBContext context)
        {
            _context = context;
        }

        // GET: Rounds
        public async Task<IActionResult> Index(int? championshipId)
        {
            ViewData["ChampionshipId"] = championshipId;
            if(championshipId != null)
            {
                // Ordena primeiro pelo Id do campeonato enviado no Details do Championship
                var dBContext = _context.Rounds.Include(r => r.Championship).Include(r => r.Circuit).Where(r => r.ChampionshipId == championshipId).OrderBy(r => r.Number);                
                return View(await dBContext.ToListAsync());
            }
            else
            {
                // Ordena primeiro pelo Year do Championship e depois pelo Number da Round
                var dBContext = _context.Rounds.Include(r => r.Championship).Include(r => r.Circuit).OrderByDescending(r => r.Championship.Year).ThenBy(r => r.Number);
                return View(await dBContext.ToListAsync());
            }          
        }

        // GET: Rounds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var round = await _context.Rounds
                .Include(r => r.Championship)
                .Include(r => r.Circuit)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (round == null)
            {
                return NotFound();
            }

            return View(round);
        }

        // GET: Rounds/Create
        public IActionResult Create(int? championshipId)
        {
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year");
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,ChampionshipId,CircuitId")] Round round)
        {
            if (ModelState.IsValid)
            {
                _context.Add(round);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", round.ChampionshipId);
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName", round.CircuitId);
            return View(round);
        }

        // GET: Rounds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var round = await _context.Rounds.FindAsync(id);
            if (round == null)
            {
                return NotFound();
            }
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", round.ChampionshipId);
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName", round.CircuitId);
            return View(round);
        }

        // POST: Rounds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,ChampionshipId,CircuitId")] Round round)
        {
            if (id != round.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(round);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoundExists(round.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChampionshipId"] = new SelectList(_context.Championships, "Id", "Year", round.ChampionshipId);
            ViewData["CircuitId"] = new SelectList(_context.Circuits, "Id", "FullName", round.CircuitId);
            return View(round);
        }

        // GET: Rounds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var round = await _context.Rounds
                .Include(r => r.Championship)
                .Include(r => r.Circuit)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (round == null)
            {
                return NotFound();
            }

            return View(round);
        }

        // POST: Rounds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var round = await _context.Rounds.FindAsync(id);
            _context.Rounds.Remove(round);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoundExists(int id)
        {
            return _context.Rounds.Any(e => e.Id == id);
        }
    }
}

F1_Project/Views/Championships/Create.cshtml
@model F1_Project.Models.Championship

@{
    ViewData["Title"] = "Create";
}

<h4>New Championship</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" />
                <a asp-action="Index" class="btn btn-primary">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

F1_Project/Views/Championships/Delete.cshtml
@model F1_Project.Models.Championship

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3><hr />
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Delete" class="btn btn-outline-danger" />
    <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Back</a>
</form>

F1_Project/Views/Championships/Details.cshtml
@model F1_Project.Models.ViewModel.DriverIndexData

@{
    ViewData["Title"] = "Details";
}

<div>    
    <a asp-controller="Rounds" asp-action="Index" asp-route-championshipid="@ViewData["ChampionshipId"]" class="btn btn-outline-info">Calendar</a>    
    <a asp-action="Edit" asp-route-id="@ViewData["ChampionshipId"]" class="btn btn-outline-secondary">Edit</a>
    <a asp-action="Delete" asp-route-id="@ViewData["ChampionshipId"]" class="btn btn-outline-danger">Delete</a>
    <a asp-action="Index" class="btn btn-primary">Back</a>
</div>
<hr />
<h4>Teams Participating:</h4>
<hr />
<div>

    <dl class="row">
        <dd class="col-sm-10">
            <ul>
                @foreach (var item in Model.Championships)
                {                    
                    if (item.Id == (int?)ViewData["ChampionshipId"])
                    {
                        @foreach (var team in item.ChampionshipTeams)
                        {
                            <li>@team.Team.FullName</li>
                        }
                    }                   
                }
            </ul>
        </dd>
    </dl>
</div>

F1_Project/Views/Championships/Edit.cshtml
@model F1_Project.Models.Championship

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Championship</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-success" />
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

F1_Project/Views/Championships/Index.cshtml
@model F1_Project.Models.ViewModel.DriverIndexData

@{
    ViewData["Title"] = "F1 Championships";
}

<h1>Championship</h1>

<p>
    <a asp-action="Create" class="btn btn-info footer-color">New Championship</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Year
            </th>
            <th>
                Teams
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Championships)
{
    string selectedRow = "";
    if (item.Id == (int?)ViewData["ChampionshipId"])
    {
        selectedRow = "table-sucess";
    }
        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td class="long-text">
                @foreach (var team in item.ChampionshipTeams)
                {
                    @team.Team.FullName;
                    @:&#47;
                }
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-secondary">Details</a>
                <a asp-controller="ChampionshipTeams" asp-action="Create" asp-route-championshipid="@item.Id" class="btn btn-outline-success">Assign Team</a>
            </td>
        </tr>
}
    </tbody>
</table>