F1_Project/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace F1_Project.Models
{
    public class Driver
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field can't be empty")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "This field must have more than 5 chars")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "This field can't be empty")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "This field must have more than 5 chars")]
        public string Nationality { get; set; }

        [Required(ErrorMessage = "This field can't be empty")]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "This field cant be less or equal than zero")]
        public int ChampionshipsVictories { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "This field cant be less or equal than zero")]
        public int RaceVictories { get; set; }

        [Range(1, 99, ErrorMessage = "This field cant be less or equal than zero")]
        public int CarNumber { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }

        // Chaves estrangeiras
        public ICollection<DriverTeam> DriverTeams { get; set; }
    }
}

F1_Project/Controllers/DriverTeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using F1_Project.Data;
using F1_Project.Models;
using Microsoft.Extensions.Logging;

namespace F1_Project.Controllers
{
    public class DriverTeamsController : Controller
    {
        private readonly DBContext _context;
        private readonly ILogger<DriverTeamsController> _logger;

        public DriverTeamsController(DBContext context ,ILogger<DriverTeamsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: DriverTeams
        public async Task<IActionResult> Index(int? id, int? teamId)
        {
            if (id != null)
            {
                var dBContext = _context.DriverTeams.Include(d => d.Driver).Include(d => d.Team).Where(d => d.DriverId == id.Value);
                return View(await dBContext.ToListAsync());
            }
            else if(teamId != null)
            {
                var dBContext = _context.DriverTeams.Include(d => d.Driver).Include(d => d.Team).Where(d => d.TeamId == teamId.Value);
                return View(await dBContext.ToListAsync());
            }
            else
            {
                var dBContext = _context.DriverTeams.Include(d => d.Driver).Include(d => d.Team);
                return View(await dBContext.ToListAsync());
            }
            
        }

        // GET: DriverTeams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driverTeam = await _context.DriverTeams
                .Include(d => d.Driver)
                .Include(d => d.Team)
                .FirstOrDefaultAsync(m => m.DriverId == id);
            if (driverTeam == null)
            {
                return NotFound();
            }

            return View(driverTeam);
        }

        // GET: DriverTeams/Create
        public IActionResult Create(int? driverId, int? teamId)
        {
            // Como Id não é chave primária, não há auto-incremento
            IEnumerable<int> ids = _context.DriverTeams.Select(dt => dt.Id).ToList();
            ViewData["NewId"] = ids.Last() + 1;

            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "FullName");
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,InitialYear,FinalYear,DriverId,TeamId")] DriverTeam driverTeam)
        {
            if (ModelState.IsValid)
            {
                _context.Add(driverTeam);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");                
            }
            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "FullName", driverTeam.DriverId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName", driverTeam.TeamId);
            return View(driverTeam);
        }

        // GET: DriverTeams/Edit/5
        public IActionResult Edit(int? driverId, int? teamId)
        {
            DriverTeam driverTeam1 = _context.DriverTeams.Find(driverId, teamId);

            if (driverTeam1 == null)
            {
                return NotFound();
            }
            
            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "FullName", driverTeam1.DriverId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName", driverTeam1.TeamId);

            return View(driverTeam1);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id,InitialYear,FinalYear,DriverId,TeamId")] DriverTeam driverTeam)
        {
            // Chaves compostas => https://www.codeproject.com/Articles/797444/ASP-NET-MVC-Edit-Primary-Key-Values-for-Composite

            if (ModelState.IsValid)
            {
                int DriverIdTemp = Convert.ToInt32(driverTeam.DriverId);
                int TeamIdTemp = Convert.ToInt32(driverTeam.TeamId);

                var services = _context.DriverTeams.Single(dt => dt.Id == driverTeam.Id);                
                _context.DriverTeams.Remove(services);
                
                _context.DriverTeams.Add(driverTeam);
                try
                {
                    _context.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Index");
                }
                _context.Entry(driverTeam).State = EntityState.Modified;              
                return RedirectToAction("Index");
            }

            ViewData["DriverId"] = new SelectList(_context.Drivers, "Id", "FullName", driverTeam.DriverId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "FullName", driverTeam.TeamId);
            return View(driverTeam);
        }

        // GET: DriverTeams/Delete/5
        public async Task<IActionResult> Delete(int? driverId, int? teamId)
        {
            if (driverId == null || teamId == null)
            {
                return NotFound();
            }

            var driverTeam = await _context.DriverTeams
                .Include(d => d.Driver)
                .Include(d => d.Team)
                .FirstOrDefaultAsync(m => m.DriverId == driverId && m.TeamId == teamId);
            if (driverTeam == null)
            {
                return NotFound();
            }

            return View(driverTeam);
        }

        // POST: DriverTeams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int driverId, int teamId)
        {
            var driverTeam = await _context.DriverTeams.FindAsync(driverId, teamId);
            _context.DriverTeams.Remove(driverTeam);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DriverTeamExists(int teamId, int driverId)
        {
            return _context.DriverTeams.Any(e => e.DriverId == driverId && e.TeamId == teamId);
        }
    }
}

F1_Project/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using F1_Project.Data;
using F1_Project.Models;
using F1_Project.Models.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace F1_Project.Controllers
{
    public class DriversController : Controller
    {
        private readonly DBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public DriversController(DBContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // Explicit Loading => https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-5.0#about-explicit-loading
        public async Task<IActionResult> Index(int? id)
        {
            var viewModel = new DriverIndexData();
            viewModel.Drivers = await _context.Drivers
                .Include(d => d.DriverTeams)
                    .ThenInclude(d => d.Team)
                .AsNoTracking().OrderBy(d => d.FullName).ToListAsync();

            if(id != null)
            {
                ViewData["DriverId"] = id.Value;                
                Driver driver = viewModel.Drivers.Where(d => d.Id == id.Value).Single();
                viewModel.Teams = driver.DriverTeams.Select(d => d.Team);
            }

            return View(viewModel);
        }

        // GET: Drivers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Drivers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // GET: Drivers/Create
        public IActionResult Create()
        {            
            return View();
        }

        // POST: Drivers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Nationality,BirthDate,CarNumber,ChampionshipsVictories,RaceVictories,Description,Photo")] Driver driver, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if(file != null)
                {
                    var linkUpload = Path.Combine(_hostEnvironment.WebRootPath, "Images");

                    using (FileStream fileStream = new FileStream(Path.Combine(linkUpload, file.FileName), FileMode.Create))
                    {                        
                        await file.CopyToAsync(fileStream);                        
                        driver.Photo = "~/Images/" + file.FileName;
                    }
                }

                _context.Add(driver);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(driver);
        }

        // GET: Drivers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Drivers.FindAsync(id);
            if (driver == null)
            {
                return NotFound();
            }

            TempData["DriverPhoto"] = driver.Photo;
            return View(driver);
        }

        // POST: Drivers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Nationality,BirthDate,CarNumber,ChampionshipsVictories,RaceVictories,Description,Photo")] Driver driver, IFormFile file)
        {
            if (id != driver.Id)
            {
                return NotFound();
            }

           // driver.Photo = TempData["DriverPhoto"].ToString();

            if (ModelState.IsValid)
            {
                if (file != null)
                {                    
                    var linkUpload = Path.Combine(_hostEnvironment.WebRootPath, "Images");

                    using (FileStream fileStream = new FileStream(Path.Combine(linkUpload, file.FileName), FileMode.Create))
                    {                        
                        await file.CopyToAsync(fileStream);                        
                        driver.Photo = "~/Images/" + file.FileName;
                    }
                }
                else
                {
                    driver.Photo = TempData["DriverPhoto"].ToString();
                }

                try
                {
                    _context.Update(driver);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DriverExists(driver.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(driver);
        }

        // GET: Drivers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Drivers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var driver = await _context.Drivers.FindAsync(id);

            string driverPhoto = driver.Photo;
            if(driver.Photo != null)
            {
                driverPhoto = driverPhoto.Replace("~", "wwwroot");
                System.IO.File.Delete(driverPhoto);
            }          
            
            _context.Drivers.Remove(driver);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DriverExists(int id)
        {
            return _context.Drivers.Any(e => e.Id == id);
        }
    }
}

F1_Project/Views/Drivers/Create.cshtml
@model F1_Project.Models.Driver

@{
    ViewData["Title"] = "Add new Driver";
    
}

<h4>New Driver</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label">Full Name</label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label">Birth Date</label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarNumber" class="control-label">Car Number</label>
                <input asp-for="CarNumber" class="form-control" />
                <span asp-validation-for="CarNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampionshipsVictories" class="control-label">Titles</label>
                <input asp-for="ChampionshipsVictories" class="form-control" value="0" />
                <span asp-validation-for="ChampionshipsVictories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RaceVictories" class="control-label">Race Victories</label>
                <input asp-for="RaceVictories" class="form-control" value="0" />
                <span asp-validation-for="RaceVictories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" type="file" class="form-control" name="file" id="file" onchange="LoadImage(this)" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <img src="#" name="file" id="file" height="160" width="240" class="border border-secondary rounded" />
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-outline-success" />
                <a asp-action="Index" class="btn btn-primary">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function LoadImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#file").attr('src', e.target.result).width(160).height(240);
                }
            }
            reader.readAsDataURL(input.files[0]);
        }
    </script>
}

F1_Project/Views/Drivers/Delete.cshtml
@model F1_Project.Models.Driver

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3><hr />
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Delete" class="btn btn-outline-danger" />
    <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Back</a>
</form>

F1_Project/Views/Drivers/Details.cshtml
@model F1_Project.Models.Driver

@{
    ViewData["Title"] = "Details";
}
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-secondary">Edit</a>
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger">Delete</a>
    <a asp-action="Index" asp-controller="DriverTeams" asp-route-id="@Model.Id" class="btn btn-outline-warning">Manage Teams</a>
    <a asp-action="Index" class="btn btn-primary">Back</a>
</div>
<hr />
<div>
    <h4>@Html.DisplayFor(model => model.FullName)</h4>
    <hr />
    <dl class="row">       
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class="col-sm-2">
            Birth Date
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            Car Number
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarNumber)
        </dd>
        <dt class="col-sm-2">
            Championship Victories
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChampionshipsVictories)
        </dd>
        <dt class="col-sm-2">
            Race Victories
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RaceVictories)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Photo != null)
            {
                <img src="@Url.Content(Model.Photo)" name="file" id="file" height="100" width="100" class="border border-secondary rounded" />
            }
            else
            {
                <img src="#" name="file" id="file" height="100" width="100" class="border border-secondary rounded" />
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>

F1_Project/Views/Drivers/Edit.cshtml
@model F1_Project.Models.Driver

@{
    ViewData["Title"] = "Edit driver information";
}

<h4>Edit Driver</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label">Full Name</label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label">Birth Date</label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarNumber" class="control-label">Car Number</label>
                <input asp-for="CarNumber" class="form-control" />
                <span asp-validation-for="CarNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChampionshipsVictories" class="control-label">Nº of Titles</label>
                <input asp-for="ChampionshipsVictories" class="form-control" />
                <span asp-validation-for="ChampionshipsVictories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RaceVictories" class="control-label">Nº of Race Victories</label>
                <input asp-for="RaceVictories" class="form-control" />
                <span asp-validation-for="RaceVictories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @if (Model.Photo != null)
                    {
                        <img src="@Url.Content(Model.Photo)" name="file" id="file" height="160" width="240" class="border border-secondary rounded" />
                    }
                    else
                    {
                        <img src="#" name="file" id="file" height="160" width="240" class="border border-secondary rounded" />
                    }
                </div>
                <div>
                    <div class="form-group">
                        <label asp-for="Photo" class="control-label"></label>
                        <input asp-for="Photo" type="file" class="form-control-file form-control-lg" name="file" id="file" onchange="LoadImage(this)" />
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-success" />
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Back</a>
            </div>
</form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    function LoadImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#file").attr('src', e.target.result).width(160).height(240);
            }
        }
        reader.readAsDataURL(input.files[0]);
    }
</script>
}

F1_Project/Views/Drivers/Index.cshtml
@model F1_Project.Models.ViewModel.DriverIndexData

@{
    ViewData["Title"] = "F1 Drivers";    
}

<h1>F1 Drivers</h1>

<p>
    <a asp-action="Create" class="btn btn-danger footer-color">New Driver</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Full Name
            </th>
            <th>
                Nationality
            </th>                     
            <th>
                Team
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Drivers)
    {
        string selectedRow = "";
        if(item.Id == (int?)ViewData["DriverId"])
        {
            selectedRow = "table-sucess";
        }

        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem => item.FullName)                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>                        
            <td class="long-text">                
                @foreach (var team in item.DriverTeams)
                {
                    @team.Team.FullName;                    
                    @:&#47;
                }
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-secondary">Details</a>
                <a asp-controller="DriverTeams" asp-action="Create" asp-route-driverid="@item.Id" class="btn btn-outline-success">Assign Team</a>           
            </td>
        </tr>
}
    </tbody>
</table>